### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by iloveck** [kan-sandbox/project-demo#1]
- [ ] add lincese file
- [ ] register
- [ ] logout

![Bad mood](https://github.com/kan-sandbox/project-demo/assets/43461406/39d860a9-e5db-4c4b-9c2e-fda3dae0dccf)

**Comment by iloveck** [comment]
@ilikems  please complete by EOD of today

**Comment by ilikems** [comment]
@iloveck  will do

**Comment by iloveck** [comment]
@ do you lic type ?

**Comment by iloveck** [comment]
@ilikems  ???

**Comment by ilikems** [comment]
@iloveck  Done
